version: "3"
services:
  spring-boot-app:
    image: spring-boot-hrms
    build:
      context: .
    ports:
      - "8089:8089"
    networks:
      - hrms-backend_mynetwork
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=HRMS
    ports:
      - "3307:3306"
    networks:
      - hrms-backend_mynetwork

networks:
  hrms-backend_mynetwork:
    driver: bridge
